# Install pre-commit:   pip3 install pre-commit
# Install hooks:        pre-commit install

repos:
    # code formatting
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black

  # code linter
- repo: https://github.com/PyCQA/flake8
  rev: 3.9.2
  hooks:
  - id: flake8