AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  showcase-data-pipeline

  Sample SAM Template for showcase-data-pipeline

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Resources:
  GetChangedProductDataFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/get_changed_product_data/
      Handler: get_changed_product_data.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Events:
        GetChangedProductDataApi:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /products
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GetChangedProductDataFunctionApi:
    Description: "API Gateway endpoint URL GetChangedProductDataFunction"
    Value: !Sub "https://${GetChangedProductDataFunctionApi}.execute-api.${AWS::Region}.amazonaws.com/products"
  GetChangedProductDataFunction:
    Description: "GetChangedProductDataFunction ARN"
    Value: !GetAtt GetChangedProductDataFunction.Arn
  GetChangedProductDataFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt GetChangedProductDataFunctionRole.Arn
