AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  showcase-data-pipeline

  Sample SAM Template for showcase-data-pipeline

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Resources:
  GetChangedProductDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/get_changed_product_data/
      Handler: get_changed_product_data.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Events:
        GetChangedProductDataApi:
          Type: HttpApi
          Properties:
            Path: /products
            Method: get

  ProductsToS3:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/products_to_s3/
      Handler: products_to_s3.lambda_handler
      Runtime: python3.10
      Layers:
        - arn:aws:lambda:REGION:us-east-1:layer:AWSSDKPandas-Python39:12  # Replace REGION and ACCOUNT_ID with your values
      Environment:
        Variables:
          ENDPOINT: my-endpoint #endpoint output from GetChangedProductDataApi
      Architectures:
        - x86_64