AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  showcase-data-pipeline

  Sample SAM Template for showcase-data-pipeline

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60


Resources:
  GetChangedProductDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/get_changed_product_data/
      Handler: get_changed_product_data.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Layers:
        - !Ref LayerAwswrangler
      Events:
        GetChangedProductDataApi:
          Type: HttpApi
          Properties:
            Path: /products
            Method: get


  ProductsToS3:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/products_to_s3/
      Handler: products_to_s3.lambda_handler
      Runtime: python3.10
      Policies: # this bucket policy is all that's necessary to allow lambda func to write to a bucket. Too easy!
        - S3WritePolicy:
            BucketName: mradobuljac-bucket
      Architectures:
        - x86_64
      Layers:
        - !Ref LayerAwswrangler
      Environment:
        Variables:
          ENDPOINT: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/products"


  LayerAwswrangler:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: awswrangler-layer
      Description: awswrangler layer made in aws sam template
      ContentUri: layers/awswrangler/ # directory containing requirements.txt file for layers
      CompatibleRuntimes:
        - python3.10
    Metadata:
      RequirementsFile: requirements.txt # name of file holding requirements. Must be located in ContentUri directory
      BuildMethod: python3.10
      BuildArchitecture: x86_64


Outputs:
  GetChangedProductDataApi:
    Description: "API Gateway endpoint URL for Prod stage for GetChangedProductData function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/products"